{
 "title": "Dockerhub Exporter Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment",
    "label": "deployment",
    "query": "label_values(deployment_dockerhub_image, name)"
   },
   {
    "name": "daemonset",
    "label": "daemonset",
    "query": "label_values(daemonset_dockerhub_image, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Pods Affected",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{deployment=~\"$deployment\"}) + sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\"$daemonset\"})"
    },
    {}
   ]
  },
  {
   "title": "% Pods Affected",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(kube_deployment_spec_replicas{deployment=~\"$deployment\"}) + sum(kube_daemonset_status_desired_number_scheduled{daemonset=~\"$daemonset\"}))/ (sum(kube_deployment_spec_replicas{}) + sum(kube_daemonset_status_desired_number_scheduled{}))"
    },
    {}
   ]
  },
  {
   "title": "Dockerhub Deployment Image",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(deployment_dockerhub_image)"
    }
   ]
  },
  {
   "title": "Dockerhub Daemonset Image",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(daemonset_dockerhub_image)"
    }
   ]
  },
  {
   "title": "Top Deployment Image",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum by(image)(deployment_dockerhub_image))"
    }
   ]
  },
  {
   "title": "Top Daemonset Image",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum by(image)(daemonset_dockerhub_image))"
    }
   ]
  }
 ]
}