name: Master

on:
  push:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Check out code
        uses: actions/checkout@v2
      - name: Lint golang code
        run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        run: make test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build binary
        run: make build
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zufardhiyaulhaq/dockerhub-exporter:latest
