name: Publish

on:
  create:
    tags:
      - v*

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set variables
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zufardhiyaulhaq/dockerhub-exporter:latest,zufardhiyaulhaq/dockerhub-exporter:${{ steps.vars.outputs.tag }}
